In [2]:
import numpy as np
from random import choice
from tqdm.auto import tqdm
from collections import namedtuple

In [3]:
PUZZLE_DIM = 3
action = namedtuple('Action', ['pos1', 'pos2'])

In [4]:
def available_actions(state: np.ndarray) -> list['Action']:
    x_start, y_start = [int(_[0]) for _ in np.where(state == 0)]
    actions = list()
    if x_start > 0:
        actions.append(action((x_start, y_start), (x_start-1, y_start)))
    if x_start < PUZZLE_DIM - 1:
        actions.append(action((x_start, y_start), (x_start+1, y_start)))
    if y_start > 0:
        actions.append(action((x_start, y_start), (x_start, y_start-1)))
    if y_start < PUZZLE_DIM - 1:
        actions.append(action((x_start, y_start), (x_start, y_start+1)))
    return actions

def do_action(state: np.ndarray, action: 'Action') -> np.ndarray:
    new_state = state.copy()
    new_state[action.pos1], new_state[action.pos2] = new_state[action.pos2], new_state[action.pos1]
    return new_state


In [ ]:
def manhattan_distance(state: np.ndarray) -> int:
    total_distance = 0
    correct_pos = {n : (n // PUZZLE_DIM, n - PUZZLE_DIM * (n // PUZZLE_DIM)) for n in range(PUZZLE_DIM**2)}
    for n in range(PUZZLE_DIM**2):
        x_current, y_current = [int(_[0]) for _ in np.where(state == n)]
        total_distance += abs(x_current - correct_pos[n][0]) + abs(y_current - correct_pos[n][1])
    return total_distance

In [33]:
RANDOMIZE_STEPS = 100_000
state = np.array([i for i in range(0, PUZZLE_DIM**2)]).reshape((PUZZLE_DIM, PUZZLE_DIM))
# for step in tqdm(range(RANDOMIZE_STEPS), desc = 'Randomizing', dynamic_ncols=True):
for step in range(RANDOMIZE_STEPS):
    state = do_action(state, choice(available_actions(state)))
print(state)
manhattan_distance(state)

[[0 5 1]
 [4 6 2]
 [3 7 8]]
0 contributes with a distance of 0 from 0,0 to 0,0
1 contributes with a distance of 1 from 0,2 to 0,1
2 contributes with a distance of 1 from 1,2 to 0,2
3 contributes with a distance of 1 from 2,0 to 1,0
4 contributes with a distance of 1 from 1,0 to 1,1
5 contributes with a distance of 2 from 0,1 to 1,2
6 contributes with a distance of 2 from 1,1 to 2,0
7 contributes with a distance of 0 from 2,1 to 2,1
8 contributes with a distance of 0 from 2,2 to 2,2


8